In [1]:
import pandas as pd
import random

In [23]:
catalog = {
    "Electronics": {
        "brands": ["Dell", "HP", "Lenovo", "Apple", "Samsung", "Asus", "Acer", "MSI"],
        "products": [
            "Laptop", "Gaming Laptop", "Desktop", "Monitor", "Keyboard",
            "Mouse", "Printer", "Scanner", "Router", "Tablet",
            "Smart Watch", "Earbuds", "SSD", "Hard Drive", "Webcam"
        ]
    },

    "Furniture": {
        "brands": ["Godrej", "IKEA", "Nilkamal", "Durian", "Urban Ladder"],
        "products": [
            "Office Chair", "Office Desk", "Bookshelf", "Cabinet",
            "Dining Table", "Coffee Table", "Wardrobe", "Sofa",
            "Bed Frame", "TV Unit"
        ]
    },

    "Clothing": {
        "brands": ["Nike", "Adidas", "Puma", "Levis", "Zara", "H&M"],
        "products": [
            "T-Shirt", "Jeans", "Jacket", "Shoes", "Cap",
            "Hoodie", "Shorts", "Sweater", "Socks", "Track Pants"
        ]
    },

    "Grocery": {
        "brands": ["Amul", "Nestle", "Britannia", "Tata", "Aashirvaad"],
        "products": [
            "Milk", "Butter", "Tea", "Coffee", "Rice",
            "Sugar", "Salt", "Biscuits", "Cooking Oil", "Pasta"
        ]
    },

    "Beauty": {
        "brands": ["Lakme", "Maybelline", "L'Oréal", "Nivea", "Pilgrim"],
        "products": [
            "Face Wash", "Moisturizer", "Shampoo", "Conditioner",
            "Serum", "Sunscreen", "Lipstick", "Foundation", "Perfume", "Body Lotion"
        ]
    },

    "Sports": {
        "brands": ["Nike", "Adidas", "Puma", "Yonex", "Cosco"],
        "products": [
            "Football", "Cricket Bat", "Basketball", "Tennis Racket",
            "Yoga Mat", "Dumbbells", "Skipping Rope", "Badminton Shuttle", "Helmet", "Gloves"
        ]
    },

    "Stationery": {
        "brands": ["Classmate", "Camel", "Faber-Castell", "Navneet"],
        "products": [
            "Notebook", "Pen", "Pencil", "Eraser", "Marker",
            "Highlighter", "Geometry Box", "Sticky Notes", "Stapler", "File Folder"
        ]
    },

    "Home Appliances": {
        "brands": ["LG", "Samsung", "Whirlpool", "IFB", "Bosch"],
        "products": [
            "Refrigerator", "Washing Machine", "Microwave",
            "Air Conditioner", "Vacuum Cleaner", "Mixer Grinder",
            "Electric Kettle", "Water Purifier", "Ceiling Fan", "Iron"
        ]
    },

    "Toys": {
        "brands": ["Lego", "Funskool", "Barbie", "Hot Wheels"],
        "products": [
            "Building Blocks", "Toy Car", "Puzzle", "Doll",
            "Remote Car", "Action Figure", "Board Game", "Toy Train", "Soft Toy", "Robot Toy"
        ]
    },

    "Automotive": {
        "brands": ["Bosch", "Castrol", "Michelin", "Exide"],
        "products": [
            "Car Battery", "Engine Oil", "Tyre", "Air Filter",
            "Spark Plug", "Car Cover", "Helmet", "Bike Chain", "Brake Pads", "Wiper Blade"
        ]
    }
}

In [3]:
category = random.choice(list(catalog.keys()))

brand = random.choice(catalog[category]["brands"])

product = random.choice(catalog[category]["products"])

print("Category:", category)
print("Brand:", brand)
print("Product:", product)

Category: Furniture
Brand: Godrej
Product: Office Desk

In [5]:
products_df = pd.DataFrame(
    product_data,
    columns=[
        "Product_ID",
        "Product_Name",
        "Category",
        "Brand",
        "Unit_Cost",
        "Unit_Price"
    ]
)

products_df

    Product_ID   Product_Name     Category Brand  Unit_Cost  Unit_Price
0          101    Dell Laptop  Electronics  Dell      40942       49695
1          102   Dell Monitor  Electronics  Dell      40050       54231
2          103  Dell Keyboard  Electronics  Dell      46773       54240
3          104     Dell Mouse  Electronics  Dell      18068       23519
4          105   Dell Printer  Electronics  Dell       9687       11461
..         ...            ...          ...   ...        ...         ...
83         184    Tata Butter      Grocery  Tata      42482       56589
84         185       Tata Tea      Grocery  Tata      17057       23517
85         186    Tata Coffee      Grocery  Tata      16040       19808
86         187      Tata Rice      Grocery  Tata      44423       55178
87         188     Tata Sugar      Grocery  Tata       3251        3974

[88 rows x 6 columns]

In [6]:
print("Total Products:", len(products_df))

Total Products: 88

In [7]:
products_df.to_csv("../Dataset/Products.csv", index=False)

print("Products.csv saved successfully!")

Products.csv saved successfully!

In [8]:
supplier_names = [
    "ABC Electronics",
    "Global Traders",
    "Prime Supplies",
    "Elite Distributors",
    "Sunrise Imports",
    "BlueSky Logistics",
    "Future Retail Supply",
    "Metro Wholesale",
    "Star Supply Chain",
    "Rapid Distributors"
]

countries = [
    "India",
    "China",
    "USA",
    "Germany",
    "Japan",
    "UAE"
]

In [9]:
supplier_data = []

In [10]:
for i in range(50):

    supplier_id = f"S{i+1:03}"

    supplier_name = random.choice(supplier_names) + " " + str(i + 1)

    country = random.choice(countries)

    lead_time = random.randint(3, 20)

    rating = round(random.uniform(3.5, 5.0), 1)

    supplier_data.append([
        supplier_id,
        supplier_name,
        country,
        lead_time,
        rating
    ])

In [11]:
supplier_id = f"S{i+1:03}"

In [12]:
rating = round(random.uniform(3.5, 5.0), 1)

In [13]:
suppliers_df = pd.DataFrame(
    supplier_data,
    columns=[
        "Supplier_ID",
        "Supplier_Name",
        "Country",
        "Lead_Time_Days",
        "Rating"
    ]
)

suppliers_df

   Supplier_ID            Supplier_Name  Country  Lead_Time_Days  Rating
0         S001         Prime Supplies 1  Germany              10     4.9
1         S002   Future Retail Supply 2    India              20     3.6
2         S003      BlueSky Logistics 3      USA              13     3.5
3         S004     Elite Distributors 4    China              16     5.0
4         S005         Prime Supplies 5  Germany               9     4.9
5         S006         Global Traders 6      UAE              17     4.1
6         S007     Rapid Distributors 7    China               7     4.3
7         S008     Elite Distributors 8    India              17     3.7
8         S009   Future Retail Supply 9    China               3     4.8
9         S010     Star Supply Chain 10      USA               6     4.7
10        S011     Star Supply Chain 11      USA              10     4.9
11        S012  Future Retail Supply 12      USA               5     4.7
12        S013    Rapid Distributors 13    India              20     4.4
13        S014       ABC Electronics 14      UAE              17     3.7
14        S015  Future Retail Supply 15    India              17     4.8
15        S016    Elite Distributors 16      UAE              13     4.7
16        S017     BlueSky Logistics 17    India              14     4.3
17        S018    Elite Distributors 18    India               6     4.7
18        S019    Elite Distributors 19    Japan               7     4.9
19        S020  Future Retail Supply 20    India              20     4.8
20        S021       Sunrise Imports 21      USA               9     4.2
21        S022     BlueSky Logistics 22    Japan              18     3.7
22        S023       ABC Electronics 23    China               8     4.5
23        S024     Star Supply Chain 24    China              14     4.4
24        S025     Star Supply Chain 25      USA              15     4.9
25        S026        Global Traders 26      UAE               8     4.2
26        S027       ABC Electronics 27    Japan               6     4.0
27        S028        Global Traders 28  Germany              11     4.3
28        S029    Rapid Distributors 29  Germany               9     4.8
29        S030       Sunrise Imports 30  Germany              13     4.4
30        S031  Future Retail Supply 31  Germany               3     5.0
31        S032    Rapid Distributors 32  Germany              19     3.6
32        S033     Star Supply Chain 33    India               7     3.8
33        S034     BlueSky Logistics 34      USA               8     4.8
34        S035     BlueSky Logistics 35    Japan               8     3.6
35        S036       Metro Wholesale 36    Japan               3     4.1
36        S037     BlueSky Logistics 37    Japan               3     4.8
37        S038       Metro Wholesale 38    India              14     3.8
38        S039       ABC Electronics 39      UAE              10     4.0
39        S040       Sunrise Imports 40    China              20     4.4
40        S041  Future Retail Supply 41      UAE              17     4.6
41        S042       ABC Electronics 42  Germany               4     4.8
42        S043    Elite Distributors 43  Germany               3     3.7
43        S044  Future Retail Supply 44      USA              11     4.2
44        S045        Prime Supplies 45      UAE               3     3.7
45        S046        Prime Supplies 46    Japan              20     4.8
46        S047       Metro Wholesale 47    Japan              10     4.4
47        S048       ABC Electronics 48    India              14     4.7
48        S049    Rapid Distributors 49      USA               3     3.6
49        S050        Prime Supplies 50    India               9     3.9

In [14]:
suppliers_df.to_csv("../Dataset/Suppliers.csv", index=False)

print("Suppliers.csv created successfully!")

Suppliers.csv created successfully!

In [15]:
len(suppliers_df)

50

In [16]:
print(suppliers_df.shape)

(50, 5)

In [17]:
cities = [
    "Hyderabad",
    "Mumbai",
    "Delhi",
    "Bengaluru",
    "Chennai",
    "Kolkata",
    "Pune",
    "Ahmedabad",
    "Jaipur",
    "Lucknow"
]

regions = {
    "Hyderabad": "South",
    "Mumbai": "West",
    "Delhi": "North",
    "Bengaluru": "South",
    "Chennai": "South",
    "Kolkata": "East",
    "Pune": "West",
    "Ahmedabad": "West",
    "Jaipur": "North",
    "Lucknow": "North"
}

In [18]:
warehouse_data = []

In [19]:
for i, city in enumerate(cities, start=1):

    warehouse_id = f"W{i:03}"

    warehouse_name = city + " Warehouse"

    region = regions[city]

    capacity = random.randint(3000, 10000)

    warehouse_data.append([
        warehouse_id,
        warehouse_name,
        city,
        region,
        capacity
    ])

In [20]:
warehouses_df = pd.DataFrame(
    warehouse_data,
    columns=[
        "Warehouse_ID",
        "Warehouse_Name",
        "City",
        "Region",
        "Capacity"
    ]
)

warehouses_df

  Warehouse_ID       Warehouse_Name       City Region  Capacity
0         W001  Hyderabad Warehouse  Hyderabad  South      3798
1         W002     Mumbai Warehouse     Mumbai   West      3504
2         W003      Delhi Warehouse      Delhi  North      5305
3         W004  Bengaluru Warehouse  Bengaluru  South      4576
4         W005    Chennai Warehouse    Chennai  South      8683
5         W006    Kolkata Warehouse    Kolkata   East      3030
6         W007       Pune Warehouse       Pune   West      8008
7         W008  Ahmedabad Warehouse  Ahmedabad   West      5161
8         W009     Jaipur Warehouse     Jaipur  North      7966
9         W010    Lucknow Warehouse    Lucknow  North      5845

In [21]:
warehouses_df.to_csv("../Dataset/Warehouses.csv", index=False)

print("Warehouses.csv created successfully!")

Warehouses.csv created successfully!

In [22]:
print(warehouses_df.shape)

(10, 5)

In [24]:
print(catalog.keys())

dict_keys(['Electronics', 'Furniture', 'Clothing', 'Grocery', 'Beauty', 'Sports', 'Stationery', 'Home Appliances', 'Toys', 'Automotive'])

In [25]:
product_data = []

product_id = 101

for category in catalog:

    brands = catalog[category]["brands"]
    products = catalog[category]["products"]

    for brand in brands:

        for product in products:

            unit_cost = random.randint(500, 50000)

            unit_price = int(unit_cost * random.uniform(1.15, 1.40))

            product_data.append([
                product_id,
                brand + " " + product,
                category,
                brand,
                unit_cost,
                unit_price
            ])

            product_id += 1

In [26]:
products_df = pd.DataFrame(
    product_data,
    columns=[
        "Product_ID",
        "Product_Name",
        "Category",
        "Brand",
        "Unit_Cost",
        "Unit_Price"
    ]
)

products_df

     Product_ID        Product_Name     Category  Brand  Unit_Cost  Unit_Price
0           101         Dell Laptop  Electronics   Dell      14943       18203
1           102  Dell Gaming Laptop  Electronics   Dell       5280        6538
2           103        Dell Desktop  Electronics   Dell      48116       55459
3           104        Dell Monitor  Electronics   Dell      41099       49466
4           105       Dell Keyboard  Electronics   Dell      42403       56011
..          ...                 ...          ...    ...        ...         ...
545         646     Exide Car Cover   Automotive  Exide       4952        6122
546         647        Exide Helmet   Automotive  Exide      37073       45523
547         648    Exide Bike Chain   Automotive  Exide      31931       42068
548         649    Exide Brake Pads   Automotive  Exide      36087       42373
549         650   Exide Wiper Blade   Automotive  Exide      16237       21812

[550 rows x 6 columns]

In [27]:
print(products_df.shape)

(550, 6)

In [28]:
products_df.to_csv("../Dataset/Products.csv", index=False)

print("Products.csv updated successfully!")

Products.csv updated successfully!

In [29]:
product_ids = products_df["Product_ID"].tolist()

supplier_ids = suppliers_df["Supplier_ID"].tolist()

warehouse_ids = warehouses_df["Warehouse_ID"].tolist()

In [30]:
inventory_data = []

In [31]:
inventory_id = 1

for product_id in product_ids:

    for warehouse_id in warehouse_ids:

        supplier_id = random.choice(supplier_ids)

        stock_quantity = random.randint(50, 1000)

        reorder_level = random.randint(20, 200)

        inventory_data.append([
            f"I{inventory_id:05}",
            product_id,
            warehouse_id,
            supplier_id,
            stock_quantity,
            reorder_level
        ])

        inventory_id += 1

In [32]:
inventory_df = pd.DataFrame(
    inventory_data,
    columns=[
        "Inventory_ID",
        "Product_ID",
        "Warehouse_ID",
        "Supplier_ID",
        "Stock_Quantity",
        "Reorder_Level"
    ]
)

inventory_df

,Inventory_ID,Product_ID,Warehouse_ID,Supplier_ID,Stock_Quantity,Reorder_Level
0,I00001,101,W001,S027,338,33
1,I00002,101,W002,S024,210,183
2,I00003,101,W003,S001,336,135
3,I00004,101,W004,S043,822,164
4,I00005,101,W005,S043,462,124
...,...,...,...,...,...,...
5495,I05496,650,W006,S038,375,123
5496,I05497,650,W007,S029,508,119
5497,I05498,650,W008,S032,308,193
5498,I05499,650,W009,S037,701,61
5499,I05500,650,W010,S003,914,139

In [33]:
print(inventory_df.shape)

(5500, 6)

In [34]:
inventory_df.to_csv("../Dataset/Inventory.csv", index=False)

print("Inventory.csv created successfully!")

Inventory.csv created successfully!

In [35]:
from datetime import datetime, timedelta

In [36]:
start_date = datetime(2025, 1, 1)

In [37]:
orders_data = []

In [38]:
order_id = 1

for i in range(50000):

    product = products_df.sample(1).iloc[0]

    warehouse = random.choice(warehouse_ids)

    quantity = random.randint(1, 10)

    order_date = start_date + timedelta(days=random.randint(0, 365))

    unit_price = product["Unit_Price"]

    total_amount = quantity * unit_price

    orders_data.append([
        f"O{order_id:06}",
        order_date.strftime("%Y-%m-%d"),
        product["Product_ID"],
        warehouse,
        quantity,
        unit_price,
        total_amount
    ])

    order_id += 1

In [39]:
orders_df = pd.DataFrame(
    orders_data,
    columns=[
        "Order_ID",
        "Order_Date",
        "Product_ID",
        "Warehouse_ID",
        "Quantity",
        "Unit_Price",
        "Total_Amount"
    ]
)

orders_df

,Order_ID,Order_Date,Product_ID,Warehouse_ID,Quantity,Unit_Price,Total_Amount
0,O000001,2025-10-31,392,W004,9,37096,333864
1,O000002,2025-02-22,409,W010,10,22022,220220
2,O000003,2025-03-17,304,W010,8,18934,151472
3,O000004,2025-10-27,630,W007,8,56994,455952
4,O000005,2025-06-14,619,W004,10,27592,275920
...,...,...,...,...,...,...,...
49995,O049996,2025-11-07,493,W005,7,49432,346024
49996,O049997,2025-02-08,463,W009,10,33061,330610
49997,O049998,2025-10-02,338,W002,1,55703,55703
49998,O049999,2025-12-08,324,W006,4,16727,66908
49999,O050000,2025-04-01,623,W004,9,49609,446481

In [40]:
print(orders_df.shape)

(50000, 7)

In [41]:
orders_df.to_csv("../Dataset/Orders.csv", index=False)

print("Orders.csv created successfully!")

Orders.csv created successfully!